blank_issues_enabled: false
  - name: Slack chat
    url: https://github.com/cloudnative-pg/cloudnative-pg?tab=readme-ov-file#communications
    about: Please join the slack channel and interact with our community
